const menu = [
    {
      name: "Europa",
      starter: [
        {
          title: "Bruschetta",
          ingredients: ["Brot", "Tomaten", "Knoblauch", "Basilikum", "Olivenöl"],
          country: "Italien",
          price: 5.5,
          quantity: 0,
        },
        {
          title: "Tapas",
          ingredients: ["Oliven", "Chorizo", "Käse", "Patatas Bravas"],
          country: "Spanien",
          price: 6.0,
          quantity: 0,
        },
        {
          title: "Antipasti",
          ingredients: ["gegrilltes Gemüse", "Oliven", "Salami", "Mozzarella"],
          country: "Italien",
          price: 7.0,
          quantity: 0,
        },
      ],
      main: [
        {
          title: "Wiener Schnitzel",
          ingredients: ["Kalbfleisch", "Paniermehl", "Ei", "Kartoffeln"],
          country: "Österreich",
          price: 18.0,
          quantity: 0,
        },
        {
          title: "Paella",
          ingredients: ["Reis", "Meeresfrüchte", "Safran", "Erbsen"],
          country: "Spanien",
          price: 20.0,
          quantity: 0,
        },
        {
          title: "Pizza Margherita",
          ingredients: ["Teig", "Tomatensauce", "Mozzarella", "Basilikum"],
          country: "Italien",
          price: 12.0,
          quantity: 0,
        },
        {
          title: "Fish and Chips",
          ingredients: ["Fischfilet", "Kartoffeln", "Erbsenpüree"],
          country: "Vereinigtes Königreich",
          price: 15.0,
          quantity: 0,
        },
        {
          title: "Lasagne",
          ingredients: ["Pasta", "Hackfleisch", "Tomatensauce", "Käse"],
          country: "Italien",
          price: 14.0,
          quantity: 0,
        },
      ],
      dessert: [
        {
          title: "Tiramisu",
          ingredients: ["Mascarpone", "Kaffee", "Löffelbiskuits", "Kakao"],
          country: "Italien",
          price: 6.5,
          quantity: 0,
        },
        {
          title: "Crème Brûlée",
          ingredients: ["Sahne", "Vanille", "Zucker", "Eier"],
          country: "Frankreich",
          price: 7.0,
          quantity: 0,
        },
        {
          title: "Pavlova",
          ingredients: ["Baiser", "Sahne", "Früchte"],
          country: "Neuseeland/Australien",
          price: 6.0,
          quantity: 0,
        },
      ],
      drinks: [
        {
          title: "Rotwein",
          ingredients: ["Trauben"],
          country: "Frankreich",
          price: 8.0,
          quantity: 0,
        },
        {
          title: "Espresso",
          ingredients: ["Kaffeebohnen"],
          country: "Italien",
          price: 2.5,
          quantity: 0,
        },
      ],
    },
    {
      name: "Asien",
      starter: [
        {
          title: "Frühlingsrollen",
          ingredients: ["Teig", "Gemüse", "Sojasauce"],
          country: "China",
          price: 4.5,
          quantity: 0,
        },
        {
          title: "Gyoza",
          ingredients: ["Teigtaschen", "Hackfleisch", "Kohl"],
          country: "Japan",
          price: 5.0,
          quantity: 0,
        },
        {
          title: "Samosas",
          ingredients: ["Teig", "Kartoffeln", "Erbsen", "Gewürze"],
          country: "Indien",
          price: 4.0,
          quantity: 0,
        },
      ],
      main: [
        {
          title: "Pad Thai",
          ingredients: ["Reisnudeln", "Eier", "Tofu", "Erdnüsse"],
          country: "Thailand",
          price: 12.0,
          quantity: 0,
        },
        {
          title: "Sushi",
          ingredients: ["Reis", "Fisch", "Nori", "Sojasauce"],
          country: "Japan",
          price: 18.0,
          quantity: 0,
        },
        {
          title: "Chicken Tikka Masala",
          ingredients: ["Hähnchen", "Tomatensauce", "Gewürze", "Reis"],
          country: "Indien",
          price: 15.0,
          quantity: 0,
        },
        {
          title: "Pho",
          ingredients: ["Brühe", "Reisnudeln", "Rindfleisch", "Kräuter"],
          country: "Vietnam",
          price: 13.0,
          quantity: 0,
        },
        {
          title: "Bibimbap",
          ingredients: ["Reis", "Gemüse", "Fleisch", "Gochujang"],
          country: "Südkorea",
          price: 14.0,
          quantity: 0,
        },
      ],
      dessert: [
        {
          title: "Mochi",
          ingredients: ["Reismehl", "Zucker", "Füllung"],
          country: "Japan",
          price: 5.0,
          quantity: 0,
        },
        {
          title: "Mango Sticky Rice",
          ingredients: ["Klebreis", "Kokosmilch", "Mango"],
          country: "Thailand",
          price: 6.5,
          quantity: 0,
        },
        {
          title: "Gulab Jamun",
          ingredients: ["Milchpulver", "Zucker", "Rosenwasser"],
          country: "Indien",
          price: 4.5,
          quantity: 0,
        },
      ],
      drinks: [
        {
          title: "Grüner Tee",
          ingredients: ["Teeblätter"],
          country: "China",
          price: 3.0,
          quantity: 0,
        },
        {
          title: "Lassi",
          ingredients: ["Joghurt", "Wasser", "Zucker", "Gewürze"],
          country: "Indien",
          price: 4.0,
          quantity: 0,
        },
      ],
    },
    {
      name: "Afrika",
      starter: [
        {
          title: "Sambusa",
          ingredients: ["Teig", "Hackfleisch", "Gewürze"],
          country: "Äthiopien",
          price: 3.5,
          quantity: 0,
        },
        {
          title: "Bunny Chow",
          ingredients: ["Brot", "Curry", "Gemüse"],
          country: "Südafrika",
          price: 5.5,
          quantity: 0,
        },
        {
          title: "Plantain Chips",
          ingredients: ["Kochbananen", "Öl", "Salz"],
          country: "Nigeria",
          price: 3.0,
          quantity: 0,
        },
      ],
      main: [
        {
          title: "Jollof Rice",
          ingredients: ["Reis", "Tomaten", "Paprika", "Gewürze"],
          country: "Nigeria",
          price: 10.0,
          quantity: 0,
        },
        {
          title: "Tagine",
          ingredients: ["Fleisch", "Gemüse", "Gewürze", "Couscous"],
          country: "Marokko",
          price: 14.0,
          quantity: 0,
        },
        {
          title: "Bobotie",
          ingredients: ["Hackfleisch", "Eier", "Milch", "Gewürze"],
          country: "Südafrika",
          price: 12.0,
          quantity: 0,
        },
        {
          title: "Piri Piri Chicken",
          ingredients: ["Hähnchen", "Piri-Piri-Sauce", "Kartoffeln"],
          country: "Mosambik",
          price: 13.5,
          quantity: 0,
        },
        {
          title: "Injera mit Doro Wat",
          ingredients: ["Injera", "Huhn", "Zwiebeln", "Berbere"],
          country: "Äthiopien",
          price: 11.0,
          quantity: 0,
        },
      ],
      dessert: [
        {
          title: "Koeksisters",
          ingredients: ["Teig", "Zucker", "Gewürze"],
          country: "Südafrika",
          price: 4.0,
          quantity: 0,
        },
        {
          title: "Malva Pudding",
          ingredients: ["Mehl", "Milch", "Aprikosenmarmelade"],
          country: "Südafrika",
          price: 5.0,
          quantity: 0,
        },
        {
          title: "Coconut Macaroons",
          ingredients: ["Kokosnuss", "Zucker", "Eier"],
          country: "Ghana",
          price: 3.5,
          quantity: 0,
        },
      ],
      drinks: [
        {
          title: "Rooibos Tee",
          ingredients: ["Rooibos-Blätter"],
          country: "Südafrika",
          price: 2.5,
          quantity: 0,
        },
        {
          title: "Hibiskus Tee",
          ingredients: ["Hibiskus-Blüten"],
          country: "Nigeria",
          price: 3.0,
          quantity: 0,
        },
      ],
    },
    {
      name: "Nordamerika",
      starter: [
        {
          title: "Nachos",
          ingredients: ["Tortilla-Chips", "Käse", "Jalapeños", "Salsa"],
          country: "Mexiko",
          price: 6.0,
          quantity: 0,
        },
        {
          title: "Buffalo Wings",
          ingredients: ["Hühnerflügel", "Scharfe Sauce", "Sellerie"],
          country: "USA",
          price: 7.0,
          quantity: 0,
        },
        {
          title: "Poutine",
          ingredients: ["Pommes frites", "Bratensauce", "Käsebruch"],
          country: "Kanada",
          price: 8.0,
          quantity: 0,
        },
      ],
      main: [
        {
          title: "Burger",
          ingredients: ["Rindfleisch", "Brötchen", "Salat", "Käse", "Tomaten"],
          country: "USA",
          price: 10.0,
          quantity: 0,
        },
        {
          title: "BBQ Ribs",
          ingredients: ["Schweinerippen", "BBQ-Sauce", "Krautsalat"],
          country: "USA",
          price: 18.0,
          quantity: 0,
        },
        {
          title: "Tacos",
          ingredients: ["Tortillas", "Fleisch", "Salsa", "Guacamole"],
          country: "Mexiko",
          price: 12.0,
          quantity: 0,
        },
        {
          title: "Clam Chowder",
          ingredients: ["Muscheln", "Kartoffeln", "Sahne", "Zwiebeln"],
          country: "USA",
          price: 14.0,
          quantity: 0,
        },
        {
          title: "Pulled Pork Sandwich",
          ingredients: ["Schweinefleisch", "Brötchen", "BBQ-Sauce"],
          country: "USA",
          price: 11.0,
          quantity: 0,
        },
      ],
      dessert: [
        {
          title: "Cheesecake",
          ingredients: ["Frischkäse", "Keksboden", "Zucker"],
          country: "USA",
          price: 6.5,
          quantity: 0,
        },
        {
          title: "Apple Pie",
          ingredients: ["Äpfel", "Teig", "Zucker", "Zimt"],
          country: "USA",
          price: 5.5,
          quantity: 0,
        },
        {
          title: "Brownie",
          ingredients: ["Schokolade", "Mehl", "Eier", "Zucker"],
          country: "USA",
          price: 4.5,
          quantity: 0,
        },
      ],
      drinks: [
        {
          title: "Coca-Cola",
          ingredients: ["Wasser", "Zucker", "Koffein"],
          country: "USA",
          price: 2.5,
          quantity: 0,
        },
        {
          title: "Milkshake",
          ingredients: ["Milch", "Eiscreme", "Zucker"],
          country: "USA",
          price: 4.0,
          quantity: 0,
        },
      ],
    },
    {
      name: "Südamerika",
      starter: [
        {
          title: "Empanadas",
          ingredients: ["Teig", "Fleisch", "Zwiebeln", "Gewürze"],
          country: "Argentinien",
          price: 5.0,
          quantity: 0,
        },
        {
          title: "Ceviche",
          ingredients: ["Fisch", "Limette", "Koriander", "Zwiebeln"],
          country: "Peru",
          price: 7.5,
          quantity: 0,
        },
        {
          title: "Arepas",
          ingredients: ["Maismehl", "Käse", "Butter"],
          country: "Venezuela",
          price: 4.5,
          quantity: 0,
        },
      ],
      main: [
        {
          title: "Feijoada",
          ingredients: ["Schwarze Bohnen", "Schweinefleisch", "Reis"],
          country: "Brasilien",
          price: 15.0,
          quantity: 0,
        },
        {
          title: "Asado",
          ingredients: ["Rindfleisch", "Gewürze", "Chimichurri"],
          country: "Argentinien",
          price: 20.0,
          quantity: 0,
        },
        {
          title: "Moqueca",
          ingredients: ["Fisch", "Kokosmilch", "Tomaten", "Paprika"],
          country: "Brasilien",
          price: 16.0,
          quantity: 0,
        },
        {
          title: "Picanha",
          ingredients: ["Rindfleisch", "Salz"],
          country: "Brasilien",
          price: 18.0,
          quantity: 0,
        },
        {
          title: "Ajiaco",
          ingredients: ["Huhn", "Kartoffeln", "Mais", "Kräuter"],
          country: "Kolumbien",
          price: 13.0,
          quantity: 0,
        },
      ],
      dessert: [
        {
          title: "Dulce de Leche",
          ingredients: ["Milch", "Zucker"],
          country: "Argentinien",
          price: 4.0,
          quantity: 0,
        },
        {
          title: "Brigadeiro",
          ingredients: ["Kondensmilch", "Kakao", "Butter"],
          country: "Brasilien",
          price: 3.5,
          quantity: 0,
        },
        {
          title: "Tres Leches Cake",
          ingredients: ["Milch", "Mehl", "Eier", "Zucker"],
          country: "Mexiko",
          price: 5.0,
          quantity: 0,
        },
      ],
      drinks: [
        {
          title: "Caipirinha",
          ingredients: ["Cachaça", "Limette", "Zucker"],
          country: "Brasilien",
          price: 7.0,
          quantity: 0,
        },
        {
          title: "Mate-Tee",
          ingredients: ["Mate-Blätter"],
          country: "Argentinien",
          price: 3.0,
          quantity: 0,
        },
      ],
    },
    {
      name: "Ozeanien",
      starter: [
        {
          title: "Prawn Cocktail",
          ingredients: ["Garnelen", "Cocktailsauce", "Salat"],
          country: "Australien",
          price: 6.5,
          quantity: 0,
        },
        {
          title: "Sausage Roll",
          ingredients: ["Blätterteig", "Wurstfüllung"],
          country: "Australien",
          price: 4.0,
          quantity: 0,
        },
        {
          title: "Kumara Chips",
          ingredients: ["Süßkartoffeln", "Öl", "Salz"],
          country: "Neuseeland",
          price: 3.5,
          quantity: 0,
        },
      ],
      main: [
        {
          title: "Lammkeule",
          ingredients: ["Lamm", "Knoblauch", "Rosmarin", "Kartoffeln"],
          country: "Neuseeland",
          price: 22.0,
          quantity: 0,
        },
        {
          title: "Barramundi",
          ingredients: ["Fisch", "Zitrone", "Kräuter"],
          country: "Australien",
          price: 18.0,
          quantity: 0,
        },
        {
          title: "Meat Pie",
          ingredients: ["Teig", "Hackfleisch", "Zwiebeln", "Soße"],
          country: "Australien",
          price: 5.0,
          quantity: 0,
        },
        {
          title: "Känguru-Steak",
          ingredients: ["Kängurufleisch", "Gewürze", "Gemüse"],
          country: "Australien",
          price: 20.0,
          quantity: 0,
        },
        {
          title: "Hangi",
          ingredients: ["Fleisch", "Gemüse", "Erdeofen"],
          country: "Neuseeland",
          price: 25.0,
          quantity: 0,
        },
      ],
      dessert: [
        {
          title: "Pavlova",
          ingredients: ["Baiser", "Sahne", "Früchte"],
          country: "Neuseeland",
          price: 6.0,
          quantity: 0,
        },
        {
          title: "Lamingtons",
          ingredients: ["Kuchen", "Kokosnuss", "Schokolade"],
          country: "Australien",
          price: 4.5,
          quantity: 0,
        },
        {
          title: "Anzac Biscuits",
          ingredients: ["Hafer", "Kokos", "Butter", "Zucker"],
          country: "Australien/Neuseeland",
          price: 3.0,
          quantity: 0,
        },
      ],
      drinks: [
        {
          title: "Flat White",
          ingredients: ["Espresso", "Milchschaum"],
          country: "Australien/Neuseeland",
          price: 3.5,
          quantity: 0,
        },
        {
          title: "Lemon, Lime and Bitters",
          ingredients: ["Limonade", "Limette", "Bitter"],
          country: "Australien",
          price: 4.0,
          quantity: 0,
        },
      ],
    },
  ];

console.log(menu)
console.table(menu)